apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadloyp6382-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadloyp6382-tenant-component
    app.kubernetes.io/part-of: loadloyp6382-tenant-app
  name: loadloyp6382-tenant-component
  namespace: loadloyp6382-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadloyp6382-tenant-component
    weight: null
status: {}
